/**
 * ZAAHI-branded Site Plan PDF — one landscape A4 page, white background,
 * gold accents, helvetica only (jsPDF built-in). Two columns:
 *   - Left (60%): map snapshot (if caller passes a maplibre map ref) OR a
 *     self-rendered polygon preview drawn from the parcel geometry.
 *   - Right (40%): Project / Dimensions / Land Use / Price / Setbacks /
 *     Notes data blocks.
 * Footer: zaahi.io · "Generated by ZAAHI Platform" · QR to the plot URL.
 *
 * Same jsPDF/helvetica stack the Feasibility Calculator already uses —
 * no new heavy deps except `qrcode` (tiny, pure JS).
 */
import { jsPDF } from 'jspdf';
import QRCode from 'qrcode';
import type { Map as MLMap } from 'maplibre-gl';

type RGB = [number, number, number];
const GOLD: RGB = [200, 169, 110];
const DARK: RGB = [51, 51, 51];
const GRAY: RGB = [107, 114, 128];
const FAINT: RGB = [180, 180, 180];

interface LandUse {
  category: string;
  sub: string;
  areaSqm: number | null;
}
interface Setback {
  side: number;
  building: number | null;
  podium: number | null;
  label?: string;
}
interface Plan {
  projectName: string | null;
  community: string | null;
  masterDeveloper: string | null;
  plotAreaSqm: number | null;
  plotAreaSqft: number | null;
  maxGfaSqm: number | null;
  maxGfaSqft: number | null;
  maxHeightCode: string | null;
  maxFloors: number | null;
  maxHeightMeters: number | null;
  far: number | null;
  setbacks: Setback[] | null;
  landUseMix: LandUse[] | null;
  notes: string | null;
}
interface Parcel {
  id: string;
  plotNumber: string;
  district: string;
  emirate: string;
  area: number;
  currentValuation: string | null;
  geometry?: GeoJSON.Polygon | null;
  latitude?: number | null;
  longitude?: number | null;
}

export interface SitePlanArgs {
  parcel: Parcel;
  plan: Plan | null;
  authority?: string | null;
  // If provided, the map is recentred on the parcel and its canvas is
  // captured as the left-column image. Without it, a polygon preview
  // is drawn from `parcel.geometry`.
  map?: MLMap | null;
}

// ── Map snapshot helpers ────────────────────────────────────────────

function polygonBBox(ring: GeoJSON.Position[]) {
  let minLng = Infinity, maxLng = -Infinity, minLat = Infinity, maxLat = -Infinity;
  for (const [lng, lat] of ring) {
    if (lng < minLng) minLng = lng;
    if (lng > maxLng) maxLng = lng;
    if (lat < minLat) minLat = lat;
    if (lat > maxLat) maxLat = lat;
  }
  return { minLng, maxLng, minLat, maxLat };
}

async function captureMap(
  map: MLMap,
  geom: GeoJSON.Polygon | null | undefined,
): Promise<string | null> {
  try {
    // Re-centre on the plot bbox with generous padding so tall 3D
    // extrusions stay fully in-frame. With pitch 45° a 100 m-tall
    // building projects ~70 m northward on-screen; 180 px padding on
    // all sides + maxZoom 17.5 + a final zoom-out step keeps the full
    // Signature model visible even at high zoom. animate:false so we
    // don't have to wait on easing.
    if (geom?.coordinates?.[0]?.length) {
      const bb = polygonBBox(geom.coordinates[0]);
      map.fitBounds(
        [[bb.minLng, bb.minLat], [bb.maxLng, bb.maxLat]],
        { padding: 180, duration: 0, maxZoom: 17.5, animate: false },
      );
      // Back off another half zoom step so the pitch doesn't push the
      // top of the 3D building out of the viewport.
      const z = map.getZoom();
      map.setZoom(Math.max(z - 0.5, 13));
    }
    // Wait for all tiles/sources to settle. `idle` fires once when the
    // map is fully rendered after the last source update.
    await new Promise<void>((resolve) => {
      const onIdle = () => {
        map.off('idle', onIdle);
        resolve();
      };
      map.on('idle', onIdle);
      // Safety timeout: if `idle` never fires (unusual), fall through
      // after 3s — preserveDrawingBuffer still guarantees the buffer
      // holds the last rendered frame.
      setTimeout(() => {
        map.off('idle', onIdle);
        resolve();
      }, 3000);
    });
    // Extra repaint so the buffer definitely has the latest frame.
    map.triggerRepaint();
    await new Promise((r) => requestAnimationFrame(() => r(null)));
    const canvas = map.getCanvas();
    return canvas.toDataURL('image/jpeg', 0.92);
  } catch (e) {
    console.warn('[site-plan-pdf] map capture failed:', e);
    return null;
  }
}

// Fallback: draw the polygon on a white canvas at ~2x the PDF slot size.
function drawPolygonPreview(geom: GeoJSON.Polygon | null | undefined): string | null {
  if (!geom?.coordinates?.[0]?.length) return null;
  const ring = geom.coordinates[0];
  const bb = polygonBBox(ring);
  const W = 1200, H = 800, PAD = 40;
  const canvas = document.createElement('canvas');
  canvas.width = W;
  canvas.height = H;
  const ctx = canvas.getContext('2d');
  if (!ctx) return null;

  ctx.fillStyle = '#F7F5F0';
  ctx.fillRect(0, 0, W, H);

  const sx = (W - PAD * 2) / (bb.maxLng - bb.minLng || 1);
  const sy = (H - PAD * 2) / (bb.maxLat - bb.minLat || 1);
  const s = Math.min(sx, sy);
  const offX = (W - s * (bb.maxLng - bb.minLng)) / 2;
  const offY = (H - s * (bb.maxLat - bb.minLat)) / 2;
  const px = (lng: number) => offX + (lng - bb.minLng) * s;
  const py = (lat: number) => H - (offY + (lat - bb.minLat) * s);

  ctx.beginPath();
  ring.forEach(([lng, lat], i) => {
    if (i === 0) ctx.moveTo(px(lng), py(lat));
    else ctx.lineTo(px(lng), py(lat));
  });
  ctx.closePath();
  ctx.fillStyle = 'rgba(200,169,110,0.25)';
  ctx.fill();
  ctx.strokeStyle = '#C8A96E';
  ctx.lineWidth = 3;
  ctx.stroke();

  ctx.fillStyle = '#6B7280';
  ctx.font = '18px Helvetica, Arial, sans-serif';
  ctx.fillText('polygon preview (no map snapshot available)', PAD, H - 20);

  return canvas.toDataURL('image/jpeg', 0.9);
}

// ── Formatting ──────────────────────────────────────────────────────

function fmtInt(n: number | null | undefined): string {
  if (n == null || !Number.isFinite(n)) return '—';
  return Math.round(n).toLocaleString('en-US');
}
function fmtAedBig(aed: number | null): string {
  if (aed == null) return '—';
  if (aed >= 1_000_000) return `AED ${(aed / 1_000_000).toFixed(1)}M`;
  if (aed >= 1_000) return `AED ${(aed / 1_000).toFixed(0)}K`;
  return `AED ${aed}`;
}
function fmtAedExact(aed: number | null): string {
  if (aed == null) return '—';
  return `AED ${Math.round(aed).toLocaleString('en-US')}`;
}
function aedFromFils(fils: string | null | undefined): number | null {
  if (!fils) return null;
  try { return Number(BigInt(fils)) / 100; } catch { return null; }
}

// ── Main ────────────────────────────────────────────────────────────

export async function generateSitePlanPdf(args: SitePlanArgs): Promise<void> {
  const { parcel, plan, authority, map } = args;

  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'landscape' });
  const W = 297, H = 210, M = 12;

  // Header: ZAAHI | SITE PLAN | date
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(...GOLD);
  doc.text('ZAAHI', M, 18);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(...DARK);
  doc.text('SITE PLAN', W / 2, 18, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...GRAY);
  const generatedOn = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });
  doc.text(generatedOn, W - M, 18, { align: 'right' });

  // Plot header line
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...DARK);
  doc.text(
    `Plot ${parcel.plotNumber} — ${parcel.district}, ${parcel.emirate}`,
    M, 25,
  );

  // Gold separator
  doc.setDrawColor(...GOLD);
  doc.setLineWidth(0.4);
  doc.line(M, 28, W - M, 28);

  // ── Layout: left col 60%, right col 40% ──────────────────────
  const colGap = 4;
  const leftW = (W - M * 2 - colGap) * 0.60;
  const rightW = (W - M * 2 - colGap) * 0.40;
  const leftX = M;
  const rightX = M + leftW + colGap;
  const bodyY = 32;
  const bodyH = H - bodyY - 22; // leave room for footer

  // ── Left column: map snapshot or polygon preview ──
  let mapImg: string | null = null;
  if (map) {
    mapImg = await captureMap(map, parcel.geometry);
  }
  if (!mapImg) mapImg = drawPolygonPreview(parcel.geometry);

  const mapH = bodyH - 10;
  if (mapImg) {
    try {
      doc.addImage(mapImg, 'JPEG', leftX, bodyY, leftW, mapH, undefined, 'FAST');
    } catch (e) {
      console.warn('[site-plan-pdf] addImage failed:', e);
    }
  } else {
    doc.setDrawColor(...FAINT);
    doc.setLineWidth(0.2);
    doc.rect(leftX, bodyY, leftW, mapH);
    doc.setFontSize(9);
    doc.setTextColor(...GRAY);
    doc.text('No geometry available', leftX + leftW / 2, bodyY + mapH / 2, { align: 'center' });
  }
  // Map caption: centroid (lng,lat)
  const lat = parcel.latitude ?? null;
  const lng = parcel.longitude ?? null;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(...GRAY);
  if (lng != null && lat != null) {
    doc.text(
      `Centroid: ${lng.toFixed(6)}°E, ${lat.toFixed(6)}°N`,
      leftX, bodyY + mapH + 4,
    );
  }
  doc.text('Source: ZAAHI parcel geometry', leftX + leftW, bodyY + mapH + 4, { align: 'right' });

  // ── Right column: data blocks ──
  let ry = bodyY + 2;
  const rRight = rightX + rightW;

  const rh = (t: string) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(...GOLD);
    doc.text(t.toUpperCase(), rightX, ry);
    ry += 1;
    doc.setDrawColor(...GOLD);
    doc.setLineWidth(0.2);
    doc.line(rightX, ry, rRight, ry);
    ry += 3.5;
  };
  const rrow = (label: string, value: string | null) => {
    if (value == null || value === '' || value === '—') return;
    if (ry > bodyY + bodyH - 4) return;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...GRAY);
    doc.text(label, rightX, ry);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...DARK);
    const v = doc.splitTextToSize(value, rightW - 28)[0];
    doc.text(v, rRight, ry, { align: 'right' });
    ry += 4.2;
  };
  const rwrap = (text: string, maxLines = 6) => {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(...DARK);
    const lines = doc.splitTextToSize(text, rightW).slice(0, maxLines);
    for (const line of lines) {
      if (ry > bodyY + bodyH - 3) break;
      doc.text(line, rightX, ry);
      ry += 3.2;
    }
    ry += 1;
  };
  const rgap = (n = 2) => { ry += n; };

  // PROJECT
  rh('Project');
  rrow('Name', plan?.projectName ?? null);
  rrow('Community', plan?.community ?? null);
  rrow('Master Dev', plan?.masterDeveloper ?? null);
  rrow('Authority', authority ?? null);
  rgap();

  // DIMENSIONS
  rh('Dimensions');
  const plotSqft = plan?.plotAreaSqft ?? parcel.area ?? null;
  const plotSqm = plan?.plotAreaSqm ?? (plotSqft ? plotSqft / 10.7639 : null);
  if (plotSqft && plotSqm) {
    rrow('Plot Area', `${fmtInt(plotSqft)} sqft  ·  ${fmtInt(plotSqm)} sqm`);
  }
  if (plan?.maxGfaSqft || plan?.maxGfaSqm) {
    rrow(
      'Max GFA',
      `${fmtInt(plan?.maxGfaSqft ?? null)} sqft  ·  ${fmtInt(plan?.maxGfaSqm ?? null)} sqm`,
    );
  }
  if (plan?.far != null) rrow('FAR', plan.far.toFixed(2));
  const heightBits = [
    plan?.maxHeightCode ?? null,
    plan?.maxHeightMeters != null ? `${plan.maxHeightMeters} m` : null,
  ].filter(Boolean) as string[];
  if (heightBits.length) rrow('Max Height', heightBits.join(' · '));
  if (plan?.maxFloors != null) rrow('Max Floors', String(plan.maxFloors));
  rgap();

  // LAND USE
  if (plan?.landUseMix && plan.landUseMix.length > 0) {
    rh('Land Use');
    for (const u of plan.landUseMix) {
      rrow(u.category, u.sub + (u.areaSqm ? `  ·  ${fmtInt(u.areaSqm)} sqm` : ''));
    }
    rgap();
  }

  // PRICE
  const aed = aedFromFils(parcel.currentValuation);
  if (aed != null && aed > 0) {
    rh('Price');
    rrow('Total Price', fmtAedBig(aed));
    if (plotSqft && plotSqft > 0) {
      rrow('Per sqft (Plot)', fmtAedExact(aed / plotSqft));
    }
    if (plan?.maxGfaSqft && plan.maxGfaSqft > 0) {
      rrow('Per sqft (GFA)', fmtAedExact(aed / plan.maxGfaSqft));
    }
    rgap();
  }

  // NOTES (truncated if long)
  if (plan?.notes && plan.notes.trim().length > 0) {
    rh('General Notes');
    rwrap(plan.notes.trim(), 10);
  }

  // ── Footer ─────────────────────────────────────────────────
  const footerY = H - 15;
  doc.setDrawColor(...GOLD);
  doc.setLineWidth(0.3);
  doc.line(M, footerY - 6, W - M, footerY - 6);

  // Build QR on the right
  const plotUrl = `https://zaahi.io/parcels/map?plot=${encodeURIComponent(parcel.plotNumber)}`;
  try {
    const qr = await QRCode.toDataURL(plotUrl, {
      margin: 0,
      width: 120,
      color: { dark: '#1A1A2E', light: '#FFFFFF' },
    });
    const qrSize = 14;
    doc.addImage(qr, 'PNG', W - M - qrSize, footerY - qrSize + 2, qrSize, qrSize);
  } catch (e) {
    console.warn('[site-plan-pdf] QR failed:', e);
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(...GOLD);
  doc.text('zaahi.io', M, footerY - 1);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(...GRAY);
  doc.text('Generated by ZAAHI Platform', W / 2, footerY - 1, { align: 'center' });

  doc.setFontSize(6.5);
  doc.setTextColor(...FAINT);
  doc.text(
    'This document is for informational purposes only. Not a title deed.',
    W / 2, footerY + 3, { align: 'center' },
  );

  const date = new Date().toISOString().slice(0, 10);
  doc.save(`ZAAHI_SitePlan_${parcel.plotNumber}_${date}.pdf`);
}
